CRM/CRM/Areas/Administrativo/Controllers/InicioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CRM.Areas.Administrativo.Controllers
{
    public class InicioController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

CRM/CRM/Areas/Administrativo/Views/MasterAdministrativo.cshtml
@{
    Layout = "~/Views/Master.cshtml";
}

<!-- Inicio cabecera -->
<header>
    <div class="container-fluid well">
        <div class="container">
            <figure class="fisi-logo-container pull-left">
                <img class="fisi-logo img-responsive" src="@Url.Content("~/Content/logo_fisi_unmsm.png")" alt="Logotipo de la FISI">
            </figure>
            <h2 class="text-center text-info"><strong>Módulo Administrativo</strong></h2>
        </div>
    </div>
</header>
<!-- Fin cabecera -->
<!-- Inicio barra de navegacion por módulo -->
<div class="container-navbar">
    <nav class="navbar navbar-top" role="navigation">
        <div class="container">
            <div class="row">
                <div class="nav navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse navbar-ex1-collapse">
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="@Url.Action("Index", "Inicio", new { Area = "Administrativo" })">Inicio</a>
                        </li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown">Dropdown 1<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("Accion", "Controlador", new { Area = "Administrativo" })">Link 1</a></li>
                                <li><a href="@Url.Action("Accion", "Controlador", new { Area = "Administrativo" })">Link 2</a></li>
                                <li><a href="@Url.Action("Accion", "Controlador", new { Area = "Administrativo" })">Link 3</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown">Dropdown 2<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("Accion", "Controlador", new { Area = "Administrativo" })">Link 1</a></li>
                                <li><a href="@Url.Action("Accion", "Controlador", new { Area = "Administrativo" })">Link 2</a></li>
                                <li><a href="@Url.Action("Accion", "Controlador", new { Area = "Administrativo" })">Link 3</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="@Url.Action("Accion", "Controlador", new { Area = "Administrativo" })">Link</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>
</div>
<!-- Fin barra de navegacion por módulo -->
<!--Inicio contenido vista de módulo-->
@RenderBody()
<!--Fin contenido vista de módulo-->
<br />
<!--Inicio Scripts Modulo-->
<script type="text/javascript">
    //Script para que se mantenga el navbar en la parte superior luego de hacer scroll.
    $(document).on("ready", function () {
        var a = $(".navbar-top"), b = a.offset().top, c = $("#menu-btn");
        $(window).on("scroll", function () {
            $(window).scrollTop() > b ? a.hasClass("navbar-top-fixed") || (a.addClass("navbar-top-fixed"), c.addClass("drawer-btn-fixed")) : a.hasClass("navbar-top-fixed") && (a.removeClass("navbar-top-fixed"), c.removeClass("drawer-btn-fixed"))
        });
    });
</script>
<!--Fin Scripts Modulo-->